#!/bin/bash

if [ -r ~/.profile ]; then ~/.profile; fi
case "$-" in *i*) if [ -r ~/.bashrc ]; then . ~/.bashrc; fi;; esac

# General
export PS1="\e[034m\]⚓\e[0m\] [ \e[33m\]\u\e[0m\] ]:\W\e[36m\]`__git_ps1`\[e[0m\]\n\$ "
export CLICOLOR=1
export LSCOlORS=ExFxCxDxBxegedabagacad

# Shortcuts
alias home='cd ~/Desktop'

# Application Commands
alias server='python3 -m http.server'
alias open='open .'
alias atom='atom .'
alias code='code .'

export PATH="/usr/local/sbin:$PATH"
